### ISSUE TITLE
Hardcoded path

### ISSUE THREAD

**Issue by yipinghuang1991** [nwg-piotr/obhud#2]
Thank you for this awesome package.
Today I build obhud on my new setup.

It seems that obhud is installed to `/usr/lib/python3.8/site-packages/obhud` instead of `/usr/lib/python3.7/site-packages/obhud`

`/usr/bin/obhud: line 2: cd: /usr/lib/python3.7/site-packages/obhud: No such file or directory`
`python: can't open file 'obhud.py': [Errno 2] No such file or directory`

**Comment by nwg-piotr** [comment]
LOL, I didn't think somebody else used this package. You're right, I forgot to change the path in /usr/bin/obhud, and it should be 3.8, but it was 3.7. Actually this should be packaged in a different way at all, but I haven't had any feedback on this script for months. For now I just updated the path and pushed 0.2.3-2 to AUR.

**Comment by yipinghuang1991** [comment]
Good job!
